#!/bin/sh

if test -n "$1"; then
   cat $1 > $SNAP_APP_DATA_PATH/bitalino.yaml
fi

if ! test -e $SNAP_APP_DATA_PATH/bitalino.yaml; then
   cp -f $SNAP/bitalino.yaml.default $SNAP_APP_DATA_PATH/bitalino.yaml
fi

cat $SNAP_APP_DATA_PATH/bitalino.yaml

