name: bitalino
version: 0
summary: DIY biosignals by bitalino and snappy Ubuntu Core
vendor: MWC Demo Prep Team <asac@canonical.com>
description: Bitalino - your medical appliance
icon: icon.png

config: bin/config

# device to cloud (d2c)
services:
  d2c-service:
    start: bin/d2c
    security-template: unconfined
    description: the bitalino device to cloud services

binaries:
  d2c:
    exec: bin/d2c
    security-template: unconfined

parts:
  bitlano-juju:
    plugin: python2
    requirements: bitlano-juju/requirements.txt
    build-packages: [gcc, cython, libbluetooth-dev]
    stage-packages: [libbluetooth3]
  d2c:
    plugin: copy
    files:
     d2c.py: bin/d2c
     config: bin/config
     bitalino.yaml.default: bitalino.yaml.default
    stage-packages: [python-yaml]

